### ISSUE TITLE
High latency for requests at client startup

### ISSUE THREAD

**Issue by srwilson** [googleapis/cloud-bigtable-client#2124]
I've noticed that immediately after a service is started up, the initial reported latency is very high, usually several seconds at 75p. It seems to decay pretty quickly, in line with Codahale metrics' exponential decay for histograms. 

My guess is this is caused by some initial connection setup for the first requests served by the session. What is the suggested way to avoid this? Should we send a warmup request with the client before we allow real requests to be served from these sessions? Maybe some option should be added the client to do this automatically.

The service calls `BigtableConfiguration.connect()` during the initialization phase before traffic is served. Once traffic is being served, we call `Connection.getTable()` on each request.

This graph shows 75p latency for ReadRows as reported by the bigtable client's builtin metrics. This service host was restarted at 11:32 and began serving traffic at 11:36. This is consistent for other request types and always happens at service startup.
![image](https://user-images.githubusercontent.com/836174/54002428-66634580-4103-11e9-9892-5cd052d83e34.png)

**Comment by sduskis** [comment]
First, I'm glad that you've made good use of the metrics.  (@igorbernstein2, FYI)

Yes, the first interaction with Cloud Bigtable clients is going to be significantly slower than the long term.  We've tried to fix it many times. You'll notice that theres a similar spike every hour or so as the Cloud Bigtable server terminates connections and restarts them.

**So... why is the first connection slow**
Here's what happens on startup:

1. A bunch of classloading.
2. Initiation of Credentials and SSL certificates
3. Initial contact with the Cloud Bigtable service
4. The "service" is actually 3 hops away from the underlying Bigtable server, and each hop is going to do an elaborate hand shake and some caching

** What can be done to make it faster? **

1. *Reduce classloading*.  We're working on a new client, [google-cloud-bigtable](https://github.com/googleapis/google-cloud-java/tree/master/google-cloud-clients/google-cloud-bigtable), which will have fewer dependencies and therefore less classloading.  It's in alpha right now, but beta is coming really soon.  We're confident in it enough to suggest it for production use.  However, you'll have to rely on [OpenCensus](https://github.com/census-instrumentation/opencensus-java) which does have a [DropWizard](https://github.com/census-instrumentation/opencensus-java/tree/master/contrib/dropwizard) exporter, although we suggest using the stackdriver integration.  You'd have an added bonus in an online serving system with faster starting times due to the reduced dependency list.

2. *Prime the connection.* It shouldn't be much code in the initializer. google-cloud-java will also have problems because of the credentials and the ssl loading.  It's going to be easier for you to warm up the connection in your initialization than for us to create a framework that does this for you, so we're probably not going to create that kind of framework.

3. *Improve the client*.  There are likely to be things we can do to improve startup times without priming the connection, but the impact will be negligible compared to priming the connection.  There's only so much that we can parallelize on the client side with all of the server-side handshaking.  We'll still try to improve the "non-primed" path as best we can.

-- Does this help?

**Comment by igorbernstein2** [comment]
A couple of corrections & additions:
- Unfortunately there is currently no opencensus -> dropwizard adapter. The linked adapter is to go the other way. 
- When priming the connection make sure to send at least as many requests as there are connections (by default 2x the number of cpus).
- Another optimization is to use a service account json file for authentication, this will enable the use of JWT tokens which don't require the OAuth dance

**Comment by srwilson** [comment]
Thanks a lot for the detailed answers. We can pretty easily add warmup requests to service startup so that's what we'll do for now.

My one ask might be to add something to the client itself to do this. Such as BigTable.connect(Config, boolean warmup). Internally this could send the necessary warmup requests before returning from this call. This would prevent us from implementing this logic ourselves. If that's not doable feel free to close this issue.

**Comment by srwilson** [comment]
I tried sending gets at startup time. Still seeing an increase in latency after restart: 75p latency goes from 20ms to 200ms after restart. This is what I used for warming

```
 IntStream.range(0, 50).parallel().forEach((i) -> 
           c.getTable(warmupTable).get(new Get(new byte[]{0}));
```

I also tried doing 10000 warmup requests instead of 50 and tried doing them in sequence instead of parallel. In all cases, got about the same latency jump. Any way to make this better?

**Comment by igorbernstein2** [comment]
It seems like latency went from 3 secs to 200ms on start up. Are you warming up all of the tables that will be used during start up? Also, does the application do similar queries during startup as during normal operation? I'm wondering the latency is coming from loading idle tablets

**Comment by srwilson** [comment]
Just did the warmup requests on a single table in an attempt to try to warmup the connections to the GFE's etc. For these tests I've only been restarting a single host out of 7 that stayed running and talking to the same set of Bigtable tables so the tablets themselves should be warmed up.

Sounds like there's not much else I can do here.

**Comment by igorbernstein2** [comment]
After the transition to google-cloud-java client, I'll try to address start up time. But for now, I don't think there is anything to be done. I'll close this for now
