### ISSUE TITLE
Provide explanation in documentation of the relationship between cloud-bigtable-client and google-cloud-java

### ISSUE THREAD

**Issue by jkleckner** [googleapis/cloud-bigtable-client#2194]
The page [using-the-java-client](https://github.com/googleapis/cloud-bigtable-client#using-the-java-client) should make clear the relationships between this client, the `bigtable-client-core` package, and the new [google-cloud-clients/google-cloud-bigtable](https://github.com/googleapis/google-cloud-java/tree/master/google-cloud-clients/google-cloud-bigtable) package.  The absence of this is confusing.  Perhaps a bit of a roadmap would do it?  
Cc: @igorbernstein2

**Comment by igorbernstein2** [comment]
The docs will be clarified as soon as the google-cloud-java hits GA. bigtable-client-core was supposed to be an implementation detail of the hbase adapter. However some of our customers found the hbase layer to be too cumbersome and started using bigtable-client-core. To address that need, we created the google-cloud-java client.

A potential future is:
- old bigtable-client-core gets deprecated
- hbase adapter gets rebased on top of the google-cloud-java client
- hbase adapter moves under google-cloud-contrib

However none of this can happen because the hbase adapter is GA and we can't replace its guts with a beta client. The roadmap will be flushed out in the next couple of months. I apologize for the interim confusion

**Comment by jkleckner** [comment]
That is helpful, thank you.
